name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. git checkout...

        uses: actions/checkout@master

      - name: 2. setup nodejs...

        uses: actions/setup-node@v1

      - name: 3. install hexo...

        run: |
          npm install
          npm run build

      # 提交到我们的存放静态资源的仓库

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.BLOG_DEPLOY }}
          repository-name: oliver34/oliver34.github.io # The repository the action should deploy to.
          branch: gh-pages # The branch the action should deploy to.
          folder: ./public # The folder the action should deploy.
